### PR TITLE
hm#01 Jiaqi Yu

### PR DESCRIPTION
**Pull request by jiaqiy1**
I found it hard for me to download the file I wanted in the beginning. It took me 5 minutes to find "readme.md".  The I read the guide on GitHub: Mastering Markdown and found it extremely helpful to learn Markdown. I think everyone should download that guide for future use. Pulling request was another hard task for me: I forked the wrong GitHub course page in the very beginning-- I forked the one for the winter session! I took me about an hour to find this mistake.

### CODE REVIEW

**Comment by jiaqiy1** [comment]
The correct homework is the one commented with "finally".

**Comment by szkaifeng** [comment]
Evaluation HW1 for Jiaqi

Topic					| Excellent | Satisfactory | Needs Work
Coding style				| √ |    
Coding strategy 			| √ |   
Presentation 			        | √ |   
Achievement, creativity 	        | √ |  
Ease of access 			| √ | 

Remarks: 

Congrats on your graduation. I was really impressed that you can speak four languages. 

The presentation here was clear and organized. You included 4 required elements in your biography and earn the full credit. You forgot to add "space" before the "#" like you did it in MAPSS line. My suggestion would be click the "view" button and see result of your coding before submitting it. Except that, everything goes well in your coding. 

Something I learned? Live a healthy life and prepare for hazardous weather in Chicago. 

Kai

**Comment by jiaqiy1** [comment]
To my graders:
I just noticed that the file I pulled yesterday has some subtle differences from the version I can view on my computer(e.g., there was no "#“ when I viewed my code on my computer, and I did add space before the "#” in my code, but there are still several of them on the version I submitted here), so I made some more edits on GitHub. You can find my newest version through "files changed".  Thanks!

**Comment by szkaifeng** [comment]
Evaluation HW1 for Jiaqi

Hi Jiaqi. My apologies for the previous format I gave. I saw your newly report. Great work! 
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |    yes       |              |            |
| **Coding strategy**         |     yes      |              |            |
| **Presentation**            |     yes      |              |            |
| **Achievement, creativity** |    yes       |              |            |
| **Ease of access**          |     yes      |              |            |

**Comment by sushmitavgopalan16** [comment]
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |        x   |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |     x      |              |            |
| **Ease of access**          |      x     |              |            |

Remarks:

* Excellent work! Your page looks great - you've shown proficient use of various different elements.
* Your code is clean and your page is well-formatted.
* This time, I've graded the final version you submitted. However, going forward, do keep in mind that only the version that is turned in before 11:30 AM Monday will be graded - any changes you commit will have to be made *before* the due date.

**Comment by t-a-trahan** [comment]
Evaluation HW-xx for Jane Doe
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |      x     |              |            |
| **Coding strategy**         |     x      |              |            |
| **Presentation**            |     x      |              |            |
| **Achievement, creativity** |     x      |              |            |
| **Ease of access**          |     x      |              |            |

Remarks:

* Great job! Your well-organized coding resulted in an easy-to-read bio page. Top marks for including all the necessary elements.
* I especially liked that included the places you've lived. You're exceptionally well-traveled - and I'm quite jealous!
* I didn't know that Github has a Markdown guide available! Thanks for letting us know - I'll browse through it this weekend.

-Alex Trahan

**Pull request closed without merging**
