### PR TITLE
YuyanWang hw01

### PR DESCRIPTION
**Pull request by yuyanw719**
I have followed all the instructions from the cfss website to finish this assignment. I think the most challenging part is to set up the connection between github and the R. It's very confusing when it comes to the Commit/Pull/Push commands. I asked TA for help and I hope the following use of R can be smooth.

### CODE REVIEW

**Comment by zczhu1995** [comment]
Topic | Excellent:  | Satisfactory:  | Needs work:  
-- | -- | -- | --
Coding style |✓ | |
Coding strategy |✓ | |
Presentation | |✓ |
Achievement, mastery, cleverness, creativity | |✓ |
Ease of access for instructor, compliance with course conventions for submitted work | ✓| |

This assignment is quite good. The code is without error and is easy to read. The only requirement  you missed is that you forget to add a picture in this assignment.

**Comment by fushu18** [comment]
Evaluation HW-01 for Yuyuan Wang
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |  Yes         |              |            |
| **Coding strategy**         |    Yes       |              |            |
| **Presentation**            |      Yes     |              |            |
| **Achievement, creativity** |   Yes        |              |            |
| **Ease of access, compliance with course conventions for submitted work**          |           |    yes          |            |

Remarks:

* Elaborate on above, especially for "needs work." Since this is the first assignment, I have little to say about coding style or strategy. Yuyuan has a clear presentation is clear and uses the available tools pretty well. The creativity is good, the book sharing link is very interesting. The compliance with the homework requirement could have been slight better, should the last paragraph be put in the comment. Because it may not be related to a self-introduction.
* Some specific praise? The book sharing is very creative.
* Specific constructive criticism? No big ones.

In all, good job for the first assignment.

**Comment by szkaifeng** [comment]
Evaluation HW1 for Yuyan Wang

Topic	Excellent: 	Satisfactory: 	Needs work: 
Coding style	✓		
Coding strategy	✓		
Presentation	✓		
Achievement, mastery, cleverness, creativity	✓		
Ease of access for instructor, compliance with course conventions for submitted work	✓		


Remarks: 

Yuyan’s work shows a proficiency in using markdown. It’s easy to access and includes the required elements. I don’t have any constructive suggestion so far. Selfish Gene is a book I’ve heard so many times but never actually read it. I/O psy is a new word to me. It sounds cool and I would like to learn more about it. I can’t agree more that connecting R to Github was the most challenging part in homework 1. It took me a long time to figure it out as well.

**Comment by szkaifeng** [comment]
Hi, Yuyan. Sorry about the previous format. I rearranged it. Please check. 

Kai

----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     √      |              |            |
| **Coding strategy**         |     √      |              |            |
| **Presentation**            |      √     |              |            |
| **Achievement, creativity** |    √       |              |            |
| **Ease of access**          |      √     |              |            |

**Comment by lyumuxuan** [comment]
Topic | Excellent | Satisfactory | Needs Work
------------ | ------------- | ------------ | ------------ |
Coding style | X
Coding strategy | X
Presentation | X
Achievement, creativity | X
Ease of access | X

Remarks:

- Yuyan's work has bold characters, bulletin point and a website inserted. Thus, fulling all the requirements.

- The preview of the work also looks good to me.  

- There's no specific coding strategy or style to comment about.

Overall, well done.

**Comment by sushmitavgopalan16** [comment]
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |        x   |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |     x      |              |            |
| **Ease of access**          |      x     |              |            |

Remarks

* Excellent work! Your page looks great - you've shown proficient use of various different elements.
* Commit early and often for future, longer assignments - helps you keep track and gives you versions to go back to, if required!
* In the future, you can remove the first two lines that the repository was seeded with - "hw01" etc to make for better presentation!
* Don't worry about having to tell us to grade your latest commit - Git automatically shows us your latest commit unless we specifically seek a previous commit.

**Pull request closed without merging**
