### PR TITLE
Submission for hw01 - Zhaodi Chen

### PR DESCRIPTION
**Pull request by ZhaodiChen**
This first homework is pretty challenging to me since this is my first time using Github and R markdown. I feel really confused at the beginning, even with a detailed guide at our course website.

Here is the whole process that I got the changes into README. md on Github: At first, I forked my own repository from uc-cfss / hw01, which is not difficult. Then, I carefully read the guidelines of homework workflow, and followed the steps one by one. I found it confusing when I was working on "pull from and push to Github from RStudio" part. I thought the reason I felt confused was that even though I was able to finish this work by following the guideline, I was not truly understood what I am doing. However, I gradually understood the workflow between Github and RStudio when I was getting start to do my own work!
I cloned the repository path of README. md into RStudio ( before this, I created two new projects in RStudio, which turned out not necessary for this homework), wrote my biography on RStudio according to the Github Guides: Mastering Markdown, and then used the "commit", "pull" & "push" workflow to commit changes and push them into Github. As for me, the process of writing my biography is much easier than the "pull form and push to Github from RStudio" part. Perhaps this is because the guides of Mastering Markdown part is very clear and simple to follow. At last, I pulled a request to make my work one part of class github page.

I was stuck by two problems for a while but successfully solved them. For one thing, I couldn't upload the image into Github, every time I tried that, it would lead to a 404 page. I solved this by uploading the image to the repository/myrepo and using that url. (I am willing to know if there are any better solutions!) For the other thing, I failed in writing headers at the first place. It just looked like "#My biography" on Github. Then I realized I missed the blank space between "#" and my text. I know this is a stupid problem, but it seems like these things happens often when using R.

At last, I want to thank the following materials for being so helpful: General Homework Guidelines and Github Guides: Mastering Markdown.

### CODE REVIEW

**Comment by yucheny** [comment]
Evaluation HW-xx for Zhaodi Chen
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |   √       |              |            |
| **Coding strategy**         |   √       |              |            |
| **Presentation**            |   √       |              |            |
| **Achievement, creativity** |   √       |              |            |
| **Ease of access**          |   √       |              |            |

Remarks:

* The codes are very clear.
* The brief bio provides a variety of information about you.
* I also have a friend studying sociology in Sun Yat-sen University, but he is a year younger than you :)

**Comment by shaoshuai95** [comment]
Evaluation HW01 for Zhaodi Chen
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |√          |              |            |
| **Coding strategy**         |√          |              |            |
| **Presentation**            |√          |              |            |
| **Achievement, creativity** |√          |              |            |
| **Ease of access**          |√          |              |            |


Remarks:

Generally speaking, the codes are clear and easy to understand. I can learn the basic information about Zhaodi from her biography.

To be more specific:

1.The coder elaborated the process of coding in detail, which would be very helpful for the readers to learn how she finished this homework. 

2.What I learn from you is to use headers to start a new topic like self-introduction, places, additions, etc. It makes the format look beautiful. 

3.This homework contains the following elements: headers, emphasis, lists, images and links, which fully meet the requirement. 

4.Thanks for sharing the useful materials related to the homework : )

**Comment by erikemueller** [comment]
Evaluation HW-01 for Zhaodi Chen
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     ✓+      |              |            |
| **Coding strategy**         |    ✓+       |              |            |
| **Presentation**            |      ✓ +     |             |            |
| **Achievement, creativity** |    ✓+       |              |            |
| **Ease of access**          |     ✓+     |              |            |

Remarks:

* Meets the general criteria (includes bolded & italicized text, list, header, and a link), though it retains the "hw 01 this is the repository for homework 1" within it and would be improved by this section's removal. 
* While you mentioned that you had some trouble initially, it appears that you figured out how to complete the assignment properly. Your code works and makes sense when looked at. 
* It is good that you figured out how to properly integrate your link. I initially had trouble with this and later figured out that it is necessary to include http:// so as to prevent the service from attempting to go to a specific github directory.

**Comment by cernhofer** [comment]
Evaluation HW-01 for ZhaodiChen 
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |      x     |              |            |
| **Coding strategy**         |    x       |              |            |
| **Presentation**            |           |       x       |            |
| **Achievement, creativity** |        x   |              |            |
| **Ease of access**          |     x      |              |            |

Remarks:
* Great work! Lots of fun information and new markdown elements!
* To your comments: YES- R and really all programming languages are very particular and often things that we don't think about (like spaces after # to make a header) make all the difference!

**Pull request closed without merging**
