### PR TITLE
HW 1 Kai Feng

### PR DESCRIPTION
**Pull request by szkaifeng**
It was a funny experience. I spent a lot of time trying to upload my file. I followed the homework instruction and download the repository in R studio. But after I finished my editing, I forgot to commit and pull! I backed to the material for quite a long time to find a solution. At first I mistakenly submitted a wrong file because I didn't click the "stage" button for my "readme‘’.  When I finally figured it out how to commit and pull, everything became clear to me. The result of my coding presented in my Github page. I fixed some problem based on the Rmarkdown instruction and delete the extra file in it. It took me 4 hours.

### CODE REVIEW

**Comment by yucheny** [comment]
Evaluation HW-01 for Kai Feng
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |    √     |              |            |
| **Coding strategy**         |    √      |              |            |
| **Presentation**            |    √      |              |            |
| **Achievement, creativity** |   √       |              |            |
| **Ease of access**          |   √       |              |            |

Remarks:

* The codes are very straightforward and easy to understand
* It looks like you have a good mastery of the basic formatting of R Markdown
* By the way, as a Chinese student in the department of sociology, I'm glad to see other Chinese students are also interested in sociology.

**Comment by DH1460** [comment]
Evaluation HW-1 for Kai Feng
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |   √        |              |            |
| **Coding strategy**         |   √       |              |            |
| **Presentation**            |   √      |              |            |
| **Achievement, creativity** |   √        |              |            |
| **Ease of access**          |   √        |              |            |

Well done! You covered _link_, _list_, _image_, _headline_, and _boldfont_.
I like how you list your research interests. The **list** element, _*1.*_, _*2*_, and _*3*_, in the project works very well. One thing I would add is that how you came cross to study sociology! Overall, very well done!

**Comment by fushu18** [comment]
Evaluation HW-01 for Kai Feng
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |  Yes         |              |            |
| **Coding strategy**         |    Yes       |              |            |
| **Presentation**            |      Yes     |              |            |
| **Achievement, creativity** |           |   Yes           |            |
| **Ease of access**          |   yes        |              |            |

Remarks:

* Elaborate on above, especially for "needs work." Since this is the first assignment, I have little to say about coding style or strategy. Kai has a clear presentation is clear and uses the available tools pretty well. The creativity could be just ever-so-slightly better, as the profile image could have been a more recent one. And the assignment is easy to access so I gave a top mark.
* Something I learned? Shopping and cooking is really a fantastic way to ease the pressure in Hyde Park.
* Specific constructive criticism? No big one. So far so good!

**Comment by cernhofer** [comment]
Evaluation HW-01 for szkaifeng
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x      |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |           |       x       |            |
| **Achievement, creativity** |     x      |           |            |
| **Ease of access**          |    x       |              |            |

Remarks:
* Great work! You correctly implemented a number of markdown elements!
* Side note: the more exposure you have to the whole git workflow, the easier it will become!

**Pull request closed without merging**
