### PR TITLE
Lucas Wehrwein HW1 Submission

### PR DESCRIPTION
**Pull request by LOW11**
Markdown was relatively easy to use. I had a hard time navigating GitHub this first time to figure out how to make a pull request, but once I am more familiar with these processes it seems like it shouldn't be too bad. I haven't been using computers for anything but word processing for a year or two now (seriously), so coming back to the internet and all these different GUI's is weird. But I find the work rewarding.

### CODE REVIEW

**Comment by imventura** [comment]
Evaluation HW-01 for LOW11
----------------------------------------------------
  | Topic                       | Excellent | Satisfactory | Needs Work |
  |-----------------------------|-----------|--------------|------------|
  | **Coding style**            |     *      |              |            |
  | **Coding strategy**         |     *      |              |            |
  | **Presentation**            |     *      |              |            |
  | **Achievement, creativity** |     *      |              |            |
  | **Ease of access**          |     *      |              |            |
  
  Remarks:
  
* Elaborate on above, especially for "needs work."
Presentation was well organized.

* Some specific praise?
Code is easy to read.

* Something I learned?
How to do back to back hyperlinks

* Specific constructive criticism?
Would have been great to have embeded a photo. 


* Something I know and that you, my peer, might like to know because it is relevant to something you struggled with.
To embed an image is the following:
Clode: " PhotoName "
Then, have the png image in your repository and upload it with the .md file.

**Comment by eolimpieva** [comment]
Evaluation HW-xx for Jane Doe
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |    +       |              |            |
| **Coding strategy**         |      +     |              |            |
| **Presentation**            |      +     |              |            |
| **Achievement, creativity** |      +     |              |            |
| **Ease of access**          |         |              |     +       |

Remarks:

Everything looks great! I marked the "ease of access" down because I had was with opening the links and viewing the image. While I am not sure how to help with the former, for the image problem I would recommend uploading the photo in png format to github and then embedding that link into the markdown. I did it this way: alt text.

**Comment by mirayp** [comment]
Evaluation HW-1 for Lucas Wehrwein

----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |      +     |              |            |
| **Coding strategy**         |     +      |              |            |
| **Presentation**            |     +      |              |            |
| **Achievement, creativity** |     +      |              |            |
| **Ease of access**          |      +     |              |            |

You've used 4 elements from Markdown, so the homework meets the requirements of this week. Your homework was easy to access and run. Since this week's assignment was pretty straightforward, I cannot find any points where you may need an improvement, everything seems nice and clean. I like the humble and funny approach, it has put a smile on my face!

**Review by mirayp — COMMENTED** [review]
Evaluation HW-1 for Lucas Wehrwein
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |    +       |              |            |
| **Coding strategy**         |    +       |              |            |
| **Presentation**            |     +      |              |            |
| **Achievement, creativity** |    +       |              |            |
| **Ease of access**          |     +      |              |            |

Remarks:

You've used 4 elements from Markdown, so the homework meets the requirements of this week. Your homework was easy to access and run. Since this week's assignment was pretty straightforward, I cannot find any points where you may need an improvement, everything seems nice and clean. I like the humble and funny approach, it has put a smile on my face!

**Comment by cernhofer** [comment]
Evaluation HW-01 for LOW11 
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |      x        |            |
| **Coding strategy**         |           |       x       |            |
| **Presentation**            |     x      |              |            |
| **Achievement, creativity** |     x      |              |            |
| **Ease of access**          |           |      x        |            |

Remarks:
* Good work! You used a number of new markdown elements and had some nice information included.
* Make sure to double check that your links are working.

**Pull request closed without merging**
