### PR TITLE
HarperGraf_hw01

### PR DESCRIPTION
**Pull request by harpergraf**
Markdown was pleasant to use and I think fairly useful as a basic way to prep your brain into thinking about syntax. For example, this made me realize how spaces are interpreted in code. The revisions I often had to make (bar my emoji excursions) were based off of how much space was above/below/to the side/between the lettering and its appropriate syntax. 
Re: the emoji excursions, perhaps I'm just not seeing one, but I'm curious if there is a general list somewhere of all proper names for emojis for code/Markdown. Not that this is a pressing issue, but it was rather inconvenient to have to keep inputting in different words in order to find a single emoji. 
Also, I had an interesting time of committing my changes. I had to keep hitting "Preview" first, just to get the file to pop up under the Git section to the right so I could commit changes. But the preview was often just a smattering of the written code mixed with some of the proper links/images. Hope that makes sense. 
Overall, this was a fun activity and I appreciated that you gave us instructions just to learn how to submit our assignments.

### CODE REVIEW

**Comment by LOW11** [comment]
Evaluation HW-01 for HarperGraf
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |      X        |            |
| **Coding strategy**         |     X      |           |            |
| **Presentation**            |      X     |              |            |
| **Achievement, creativity** |    X       |              |          |
| **Ease of access**          |       X    |              |            |

Remarks:

* Elaborate on above, especially for "needs work.": This work fulfills the basic requirements of the assignment. The introductory is very well written and informative, and it is clear that this fellow student is engaged in the class, and like the rest of us learning the ropes. However, the multiple commits make it ambiguous as to what commit is your actual assignment. I see in your change-notes references to many things, including emojis and whatnot. Some minutes later, I have just discovered your finished product! Wow! Very cool, utilizes the full range of possibilities.
* Some specific praise? The embedded images are particularly handsome.
* Something I learned? You provided a helpful link
* Specific constructive criticism? Perhaps do more editing locally before committing. But then again, my inability to parse what the "best" commit was could just be a function of my own misunderstandings. I think I understand now that it is better to look at "files changed" than "commits." My apologies if my review is a little inaccurate as a result.
* Something I know and that you, my peer, might like to know because it is relevant to something you struggled with. Nope, you seem to be right on man!

**Comment by nicholskl** [comment]
Evaluation HW01 for Harper Grag
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     X      |              |            |
| **Coding strategy**         |     X      |              |            |
| **Presentation**            |       X    |              |            |
| **Achievement, creativity** |     X      |              |            |
| **Ease of access**          |     X      |              |            |

Remarks:

I really enjoyed learning a little about you, and I was very happy to find such a helpful link - thanks a lot! I think that the pictures you attached were very cool and you satisfied the requirements for a satisfactory homework. I hope that you don't have too much trouble coding this year, but you seem to be on the right track! Good job!

**Comment by lyumuxuan** [comment]
Topic | Excellent | Satisfactory | Needs Work
------------ | ------------- | ------------ | ------------ |
Coding style | X
Coding strategy | X
Presentation | X
Achievement, creativity | X
Ease of access | X

Remarks:

- The emoji inserted is very creative.
- This work fulfills all the requirements, including bulletin points, bold and italicized words, different headings, images and a link.  
- The images are great.
- I really enjoyed reading your intro.

**Great job!**

**Comment by sushmitavgopalan16** [comment]
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |        x   |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |     x      |              |            |
| **Ease of access**          |      x     |              |            |

Remarks:

* Excellent work! Your page looks great - you've shown proficient use of various different elements.
* Love the emoji and the gif!
* Good job committing often!
* In the future, you can remove the first two lines that the repository was seeded with - "hw01" etc to make for better presentation!

**Pull request closed without merging**
