### PR TITLE
Submit hw01 - Shu Fu

### PR DESCRIPTION
**Pull request by fushu18**
It took me quite some time to work with Terminal on Mac. But once I got how it works, things become easier. And I strongly recommend to use Terminal to navigate around the folders, because it just feels so fancy, techy, and geeky!

For the Markdown, I just googled "how to edit markdown", the first several websites popping up are really helpful for me to do the editing. Looking forward to use that in later assignment.

### CODE REVIEW

**Comment by LOW11** [comment]
Evaluation HW-01 for fushu18
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |    X       |              |            |
| **Coding strategy**         |     X      |              |            |
| **Presentation**            |           |        X      |            |
| **Achievement, creativity** |           |      X        |            |
| **Ease of access**          |      X     |              |            |

Remarks:

* Elaborate on above, especially for "needs work.": As this is the first assignment, I had little to say about coding style or strategy. Shu Fu uses the available tools very well, though, so I gave top marks. The presentation and creativity could be just ever-so-slightly better, as the profile image and the last line are out of place. (The last line apparently being a mistaken sentence). Nonetheless, the assignment is well written, informative, and formatted properly.
* Some specific praise? I particularly appreciated the Chicago-style formatting of your published work.
* Something I learned? Political science students are apparently industrious! Congratulations on having two publications out or under review by fall of your third year.
* Specific constructive criticism? Perhaps double-check once more--I too had a hard time with uploading a jpeg, but it would be best to leave it out if it would not stick.
* Something I know and that you, my peer, might like to know because it is relevant to something you struggled with. Nothing in particular

**Comment by ZhaodiChen** [comment]
Evaluation HW-xx for Jane Doe
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |              |            |
| **Coding strategy**         |           |              |            |
| **Presentation**            |           |              |            |
| **Achievement, creativity** |           |              |            |
| **Ease of access**          |           |              |            |

Remarks:

* Elaborate on above, especially for "needs work."
* Some specific praise?
* Something I learned?
* Specific constructive criticism?
* Something I know and that you, my peer, might like to know because it is relevant to something you struggled with.

**Comment by ZhaodiChen** [comment]
Evaluation HW-xx for Jane Doe
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**       X     |           |              |            |
| **Coding strategy**    X     |           |              |            |
| **Presentation**         X   |           |              |            |
| **Achievement, creativity** X |           |              |            |
| **Ease of access**     X     |           |              |            |

Remarks:

* Elaborate on above, especially for "needs work.": I think Shu Fu have done a great work here. The coding style as well as strategy are clear enough for me to understand, also, the presentation includes a lot of information about him. In conclude, the assignment is fully achieved, so I gave top marks to it.
* Some specific praise? The detailed biography! And I think we share some same research interests.
* Something I learned? You formatted your work at a neat way, which is a good personal style especially when you are coding.
* Specific constructive criticism? I don't have criticism about the coding part, but maybe some more personal information in the biography, like your hobbies?
* Something I know and that you, my peer, might like to know because it is relevant to something you struggled with. Nothing in particular.

**Comment by ZhaodiChen** [comment]
Evaluation HW-xx for Jane Doe
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     X      |              |            |
| **Coding strategy**         |    X       |              |            |
| **Presentation**            |     X      |              |            |
| **Achievement, creativity** |       X    |              |            |
| **Ease of access**          |    X       |              |            |

Remarks:

* Elaborate on above, especially for "needs work.": I think Shu Fu have done a great work here. The coding style as well as strategy are clear enough for me to understand, also, the presentation includes a lot of information about him. In conclude, the assignment is fully achieved, so I gave top marks to it.
* Some specific praise: The detailed biography! And I think we share some same research interests.
* Something I learned: You formatted your work at a neat way, which is a good personal style especially when you are coding.
* Specific constructive criticism: I don't have criticism about the coding part, but maybe some more personal information in the biography, like your hobbies?
* Something I know and that you, my peer, might like to know because it is relevant to something you struggled with: Nothing in particular.

**Comment by ZhaodiChen** [comment]
Evaluation HW-xx for fushu18
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |      X     |              |            |
| **Coding strategy**         |      X     |              |            |
| **Presentation**            |     X      |              |            |
| **Achievement, creativity** |      X     |              |            |
| **Ease of access**          |      X     |              |            |

Remarks:

* Elaborate on above, especially for "needs work.":I think Shu Fu have done a great work here. The coding style as well as strategy are clear enough for me to understand, also, the presentation includes a lot of information about him. In conclude, the assignment is fully achieved, so I gave top marks to it.
* Some specific praise: The detailed biography! And I think we share some same research interests.
* Something I learned: You formatted your work at a neat way, which is a good personal style especially when you are coding.
* Specific constructive criticism: I don't have criticism about the coding part, but maybe some more personal information in the biography, like your hobbies?
* Something I know and that you, my peer, might like to know because it is relevant to something you struggled with: Nothing in particular.

**Comment by sushmitavgopalan16** [comment]
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |        x   |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |     x      |              |            |
| **Ease of access**          |      x     |              |            |

Remarks:

* Excellent work! Your page looks great - you've shown proficient use of various different elements.
* Your code is clean and the page looks nice and well-formatted.
* Commit early and often for future, longer assignments - helps you keep track and gives you versions to go back to, if required!
* I think you left in a couple of words by accident on the last line.

**Pull request closed without merging**
