### PR TITLE
Dan Gamarnik Homework 1

### PR DESCRIPTION
**Pull request by dgamarnik**
I thought the coding was relatively easy since it was similar to other kinds of code. The issue I had was managing the files on GitHub/GitDesktop in general. I accidentally split the file and updated the master version. Also "pushing" it was not intuitive (and I'm not exactly positive this is correctly pushing it either).

### CODE REVIEW

**Comment by dgamarnik** [comment]
For clarity,  "new update" is the latest version. Best!

**Review by zyzyxzy — COMMENTED** [review]
Evaluation HW-01 for Dan Gamarnik
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     √     |              |            |
| **Coding strategy**         |     √     |              |            |
| **Presentation**            |           |      √       |            |
| **Achievement, creativity** |     √     |              |            |
| **Ease of access**          |     √     |              |            |

Remarks:

You did an excellent work! The code is self-explanatory and the structure is clear, and you also included all the 5 elements in the file. I learned the basic information about you from a few lines of codes. One very small thing I think could make your work even better is adding a blank between “##” and “Research Interests” so that it could become a headline (I guess this is what you tried to do?). But overall you’ve done a great job!

**Comment by saniyamasood** [comment]
Great job!
The presentation was great: the picture in the beginning was aptly put, the links were working, your name was highlighted for emphasis and the research interests were put in bullet points for clarity. The only problem seemed with ##Research interests part where you perhaps had to put a space after the "##" to make that the heading.
---------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**                        |   √       |              |            |
| **Coding strategy**                  |   √        |              |            |
| **Presentation**                        |   √        |              |            |
| **Achievement, creativity**      |   √        |              |            |
| **Ease of access**                     |   √        |              |           |

**Review by saniyamasood — COMMENTED** [review]
.

**Comment by cernhofer** [comment]
Evaluation HW-01 for dgamarnik
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |       x       |            |
| **Coding strategy**         |           |       x       |            |
| **Presentation**            |           |      x        |            |
| **Achievement, creativity** |      x     |              |            |
| **Ease of access**          |     x      |              |            |

Remarks:
* Great work! You included some interesting information and a number of new markdown elements!
* Make sure to include a space after the pound sign(s) when including headers, so that they compile correctly.

**Pull request closed without merging**
