### PR TITLE
Ayman Baig HW 1

### PR DESCRIPTION
**Pull request by AymanBaig**
I had some difficulty figuring out exactly how to code for the specific things such as how to add a header or how to add a link. However, I found a tutorial on the RMarkdown website that gave instructions on basic functions. I also asked the TAs for assistance so they were a valuable resource.

### CODE REVIEW

**Comment by AymanBaig** [comment]
I had some difficulty figuring out exactly how to code for the specific things such as how to add a header or how to add a link. However, I found a tutorial on the RMarkdown website that gave instructions on basic functions. I also asked the TAs for assistance so they were a valuable resource.

**Review by mirayp — COMMENTED** [review]
Evaluation HW-1 for Ayman Baig
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |              |      ?      |
| **Coding strategy**         |           |              |      ?      |
| **Presentation**            |           |              |       ?     |
| **Achievement, creativity** |           |              |     ?       |
| **Ease of access**          |           |              |      ?      |

Remarks:

* I cannot access your homework! You pull request shows that there are zero files changed. I also tried cloning your homework to my computer and running it on R, but it also showed me a blank project. For this reason, I cannot evaluate your homework :( 
* I am also just starting with computation and had a similar problem to yours. Learning how to work with Markdown seemed easy, but I skipped forking the repo, and after writing the code, pulling and pushing. Unfortunately, I had to do it all over again then... It seems like the basics but is crucial to communicate your work to others. I would recommend you to check the "fork" and "pull requests" sections on repo to see what you have actually uploaded. The number next to Fork takes you to a timeline of when and what everyone in class edited. It can be useful in making sure if your code is on github.
* Best of luck in class!

**Comment by eolimpieva** [comment]
Evaluation HW-xx for Jane Doe
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |              |            |
| **Coding strategy**         |           |              |            |
| **Presentation**            |           |              |            |
| **Achievement, creativity** |           |              |            |
| **Ease of access**          |           |              |            |

Remarks:
Unfortunately I could not access your homework either, perhaps you have not properly submitted it. I would recommend review this page of the course, which I found extremely helpful! http://cfss.uchicago.edu/hw00_homework_guidelines.html#homework_workflow

**Comment by sushmitavgopalan16** [comment]
Hi Ayman, I think you've had trouble uploading your files - you've created a commit but there are no files in your repository. If you have any questions as to how to do this, please do come to office hours or create an issue on the discussion forum!

**Comment by bensoltoff** [comment]
No submission.

**Pull request closed without merging**
