### PR TITLE
Hw01 rcg

### PR DESCRIPTION
**Pull request by RCruzGil**
To get this done I mainly used the cheat sheet and the GitHub help site. I think I actually found it harder to turn in the homework than doing the homework itself. There's a fair amount of stuff that confuses me still, but most of it is in GitHub so far, not R Markdown.

### CODE REVIEW

**Comment by DH1460** [comment]
Evaluation HW-xx for Jane Doe
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |              |            |
| **Coding strategy**         |           |              |            |
| **Presentation**            |           |              |            |
| **Achievement, creativity** |           |              |            |
| **Ease of access**          |           |              |            |

Remarks:

* Elaborate on above, especially for "needs work."
* Some specific praise?
* Something I learned?
* Specific constructive criticism?
* Something I know and that you, my peer, might like to know because it is relevant to something you struggled with.

**Comment by ipekcinar** [comment]
Evaluation HW-xx for Jane Doe
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |   ✓        |              |            |
| **Coding strategy**         |    ✓       |              |            |
| **Presentation**            |     ✓      |              |            |
| **Achievement, creativity** |    ✓       |              |            |
| **Ease of access**          |   ✓        |              |            |

Your assignment is clear and you code is understandable. You met all the grading criteria and I shard the same concerns about github with you, I hope it will get much more clear to us soon. Overall, good job!

**Comment by shaoshuai95** [comment]
Evaluation HW01 for RCruzGil
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |√          |              |            |
| **Coding strategy**         |√          |              |            |
| **Presentation**            |√          |              |            |
| **Achievement, creativity** |√          |              |            |
| **Ease of access**          |√          |              |            |


Remarks:

Generally speaking, the codes are very clear and understandable. I can learn the basic information from this biography.

To be more specific:

1.I notice that you tried to generate the headers with "#". However, I don't know whether you have found that it didn't work. I have no idea why it happened but maybe you could try to start a new line.

2.This homework contains the following elements: headers(although it didn't work), emphasis, lists, images and links, which fully meet the requirement.

3. I really like the YouTube Video you inserted. : )

**Comment by sushmitavgopalan16** [comment]
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |        x   |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |     x      |              |            |
| **Ease of access**          |      x     |              |            |

Remarks:

* Nice work! Your page looks great - you've shown proficient use of various different elements.
* Your headers don't work because you haven't left a space between the '#' and your text - this is an easy fix! I haven't taken points off because even without headers, you have 4 working markdown elements in place. 
* In the future, you can remove the first two lines that the repository was seeded with - "hw01" etc to make for better presentation!

**Pull request closed without merging**
