### PR TITLE
Sarah Mixon

### PR DESCRIPTION
**Pull request by smixon**
I appreciate the first homework being relatively simple and an accessible introduction to R and GitHub. I've never used either of these programs so my main challenge was figuring out how to commit and push my work. A lot of my time was spent reading the Git intro book which is on GitHub, I think, and reading//practicing the tips on the class website. But, actually, Sushmita walked me through how to navigate the terminal and now I feel like a pro. 

I'm starting to feel more comfortable in R and I like that the language seems more intuitive than other programs like STATA.

### CODE REVIEW

**Comment by jingkunw** [comment]
The work is well-done. He/she includes different levels of headings, lists and images that what we are required to include in our file. However, I think he/she missed the "link" element. If you could include this, that would be much better. Overall, this file has the well-written code and nice structure.

**Review by mbokanga — COMMENTED** [review]
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     check      |              |            |
| **Coding strategy**         |   check        |              |            |
| **Presentation**            |     check      |              |            |
| **Achievement, creativity** |     check      |              |            |
| **Ease of access**          |     check      |              |            |

everything was great and the ET pic made me laugh :)

**Comment by cernhofer** [comment]
Evaluation HW-01 for smixon
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x      |              |            |
| **Coding strategy**         |     x      |              |            |
| **Presentation**            |           |      x        |            |
| **Achievement, creativity** |     x      |              |            |
| **Ease of access**          |          |        x      |            |

Remarks:
* Great work! You used a number of different markdown elements and had a very nice introduction.
* Be sure that your final product is visually coherent- for this specific assignment, it doesn't really make sense to include the hw01 header and short description at the bottom of the file.
* Side note: R is sooo much better than Stata is so many ways- get excited!

**Comment by sushmitavgopalan16** [comment]
Hi Sarah! When I recommended using stringr to remove "name" from named and namem today - I didn't realize the instructions were to only use tidyverse functions. This can be achieved with one of gather, separate, unite and spread! Good luck figuring it out!

**Pull request closed without merging**
