### PR TITLE
HW01 - Kanyao Han

### PR DESCRIPTION
**Pull request by khan1792**
The Challenge
While it is easy to manage github via SourceTree, there is still a challenge when I change the README.md via RStudio. It is difficult to change the size of images and embed it into README.md. 
My solutions are:
1. Change the size of my picture in Photoshop before embedding.
2. Create a new repository in my github for storing files, add the picture there and write a link to the picture in README.md.

A Helpful Resource
There is a Chinese website that contains a brief markdown guide of how to set "header", "emphasis", "List", "link", "images", "super-/subscript", etc.

Steps
1. Fork the repository.
2. Download SourceTree as the management software. (All the following steps are completed in SourceTree)
3. Clone (File -> Clone/New) the remote repository(in github) and pull its content into my laptop.
4. Open README.md in local repository and change it via RStudio.
5. Save the changes in RStudio and stage README.md.
6. Click "Commit" on the top left corner, input some words in the input box at the bottom and click another "Commit" on the bottom right corner.
7. Click "Push"
8. Pull Request

### CODE REVIEW

**Comment by zczhu1995** [comment]
Topic | Excellent:  | Satisfactory:  | Needs work: 
-- | -- | -- | --
Coding style |   ✓ |  | 
Coding strategy |    ✓ | | 
Presentation |   ✓|  | 
Achievement, mastery, cleverness, creativity | ✓ | |
Ease of access for instructor, compliance with course conventions for submitted work | ✓ | |

You have done this assignment well, the code is clear and easy to understand. Beyond meeting all the requirement, you've also made a beautiful page. I was impressed when I opened the page, I thought I went to your biography website, great job!

**Comment by ipekcinar** [comment]
Evaluation HW-xx for Jane Doe
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     ✓    |              |            |
| **Coding strategy**         |     ✓    |              |            |
| **Presentation**            |     ✓      |              |            |
| **Achievement, creativity** |     ✓      |              |            |
| **Ease of access**          |      ✓     |              |            |

Your assignment and comments are super clear. It gave great detail of how you did it and the end result looks really great. I definitely do not have anything to add to this, excellent job!

**Comment by yuyanw719** [comment]
Evaluation HW-01 for Kanyao Han
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     ✓      |              |            |
| **Coding strategy**         |    ✓       |              |            |
| **Presentation**            |      ✓     |              |            |
| **Achievement, creativity** |    ✓       |              |            |
| **Ease of access**          |     ✓      |              |            |

I think overall this is very good. You have met every grading criteria. Everything is very clear.

**Comment by asijilmassi** [comment]
Evaluation HW01 for Kanyao
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x      |              |            |
| **Coding strategy**         |    x       |              |            |
| **Presentation**            |        x   |              |            |
| **Achievement, creativity** |    x       |              |            |
| **Ease of access**          |      x     |              |            |

Remarks:

* Hey Kanyao ! I think your work is solid, and your presentation is aesthetically pleasant as well as it is clear.
* I would simply add a few recommandations, which I received myself from a peer because my work had the same little "flaws" as yours. 
* First, you only commited once (so did I !). It's fine but we should both get the reflex of committing more often, so we can keep track of our work's progress, and potentially be able to come back to one of the previous steps. It is *definitely* something to think about for the next assignment !
* Second, your description starts with "HW01". Maybe you could remove it in order to improve the efficiency of your text. But it's up to you, you may have a different opinion on this;

**Comment by sushmitavgopalan16** [comment]
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |        x   |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |     x      |              |            |
| **Ease of access**          |      x     |              |            |

Remarks:

* Excellent work! Your page looks great - you've shown proficient use of various different elements.
* Nice job on figuring out how to change font size. 
* Your description of your workflow is clear. 
* Commit early and often for future, longer assignments - helps you keep track and gives you versions to go back to, if required!

**Pull request closed without merging**
