### PR TITLE
Evgenia Olimpieva/Howework 1

### PR DESCRIPTION
**Pull request by eolimpieva**
I did not have any problems with understanding the workflow, the instruction were very clear. However, it was not clear that we had to submit the "pull request" from Git in order to be able to submit the homework.

### CODE REVIEW

**Comment by saniyamasood** [comment]
Great work!
All the information is clearly displayed, incorporating all the 5 elements that were required for this assignment. The picture in the beginning makes the presentation very good.

However, I can see an output box at the top of the page - which I don't really understand.


---------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     ✓      |              |            |
| **Coding strategy**         |    ✓       |              |            |
| **Presentation**            |   ✓        |              |            |
| **Achievement, creativity** |       ✓    |              |            |
| **Ease of access**          |    ✓       |              |            |

**Comment by chongyu71** [comment]
Hi Evgenia,

You did a really good job! You successfully included the headers, italics emphasis, lists, images and links. In particular, you use three different heading sizes, which made the layout well-organized. 
By the way, from your commit history (add a image), I think we encountered the same problem and fixed it in the same way - uploading the image to repo and then inserting image with the URL on repo.


### Evaluation HW-01 for Evgenia Olimpieva
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     √      |              |            |
| **Coding strategy**         |     √      |              |            |
| **Presentation**            |      √     |              |            |
| **Achievement, creativity** |     √      |              |            |
| **Ease of access**          |     √      |              |            |

**Comment by sushmitavgopalan16** [comment]
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |        x   |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |     x      |              |            |
| **Ease of access**          |      x     |              |            |

Remarks:

* Excellent work! Your page looks great - you've shown proficient use of various different elements.
* Your code and your workflow are clear.
* Commit early and often for future, longer assignments - helps you keep track and gives you versions to go back to, if required!

**Comment by sushmitavgopalan16** [comment]
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |        x   |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |     x      |              |            |
| **Ease of access**          |      x     |              |            |

Remarks:

* Excellent work! Your page looks great - you've shown proficient use of various different elements.
* Your code and workflow are clear.
* Nice use of commits - keep committing early and often!

**Pull request closed without merging**
